#!/bin/bash

# Usage: build [targets]
# Run make [targets] in every subdirectory containing a Makefile

runCmd () {
	printf "\033[1m$*\033[0m\n" 1>&2
	$*
	if [ "$?" == "0" ]; then
		printf "\033[1m\033[32m$*\033[0m\n" 1>&2
	else
		printf "\033[1m\033[31m$*\033[0m\n" 1>&2
	fi
}

makeflags_file=".make_flags"
[ -e "$makeflags_file" ] || runCmd touch "$makeflags_file"

makeflags=$(runCmd cat "$makeflags_file")

for mf in `find . -iname makefile`; do
	dir=$(dirname $mf)
	runCmd make $makeflags -C $dir $*
done
