

PKGCONFIG = PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/ pkg-config

CPPFLAGS = -I/Library/Frameworks/SFML.framework/Headers/ -I../common
LIBS = ../common/model/libmodel.a ../common/json/libjson.a

all: testsfml.app
	./$<

include ../Makefile.includes

LDFLAGS += -framework sfml-system -framework sfml-graphics -framework sfml-window
